name: "CI"
on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix
        run: nix profile install nixpkgs#omnix
      - name: om show
        run: om show .
      - name: om ci
        run: om ci run --extra-access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" --systems "${{ matrix.system }}"
      - name: om init tests
        run: |
          om init --test .

